/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 52
#define LARGE_STATE_COUNT 5
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_doctype = 1,
  anon_sym_LT = 2,
  anon_sym_GT = 3,
  anon_sym_LT_SLASH = 4,
  anon_sym_SLASH = 5,
  anon_sym_EQ = 6,
  sym_quoted_attribute_value = 7,
  sym_unquoted_attribute_value = 8,
  sym_tag_name = 9,
  sym_attribute_name = 10,
  sym__tag_whitespace = 11,
  sym_entity = 12,
  sym_plain_ampersand = 13,
  sym_text = 14,
  sym_document = 15,
  sym__node = 16,
  sym_element = 17,
  sym_start_tag = 18,
  sym_end_tag = 19,
  sym_self_closing_element = 20,
  sym_attribute = 21,
  sym_attribute_value = 22,
  aux_sym_document_repeat1 = 23,
  aux_sym_start_tag_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_doctype] = "doctype",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ] = "=",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_unquoted_attribute_value] = "unquoted_attribute_value",
  [sym_tag_name] = "tag_name",
  [sym_attribute_name] = "attribute_name",
  [sym__tag_whitespace] = "_tag_whitespace",
  [sym_entity] = "entity",
  [sym_plain_ampersand] = "plain_ampersand",
  [sym_text] = "text",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_element] = "self_closing_element",
  [sym_attribute] = "attribute",
  [sym_attribute_value] = "attribute_value",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_doctype] = sym_doctype,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_unquoted_attribute_value] = sym_unquoted_attribute_value,
  [sym_tag_name] = sym_tag_name,
  [sym_attribute_name] = sym_attribute_name,
  [sym__tag_whitespace] = sym__tag_whitespace,
  [sym_entity] = sym_entity,
  [sym_plain_ampersand] = sym_plain_ampersand,
  [sym_text] = sym_text,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_element] = sym_self_closing_element,
  [sym_attribute] = sym_attribute,
  [sym_attribute_value] = sym_attribute_value,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_doctype] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym__tag_whitespace] = {
    .visible = false,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [sym_plain_ampersand] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_element] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(19);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '&') ADVANCE(72);
      if (lookahead == '\'') ADVANCE(3);
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '<') ADVANCE(21);
      if (lookahead == '=') ADVANCE(25);
      if (lookahead == '>') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '`') ADVANCE(27);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(26);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(26);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '/') ADVANCE(24);
      if (lookahead == '>') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(29);
      END_STATE();
    case 5:
      if (lookahead == '>') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(20);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(20);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(13);
      END_STATE();
    case 9:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 10:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(5);
      END_STATE();
    case 11:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 12:
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(10);
      END_STATE();
    case 13:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(15);
      END_STATE();
    case 14:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(17);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(37);
      END_STATE();
    case 15:
      if (lookahead == 'Y' ||
          lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 16:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(6);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(7);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 18:
      if (eof) ADVANCE(19);
      if (lookahead == '&') ADVANCE(72);
      if (lookahead == '<') ADVANCE(21);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0) ADVANCE(73);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_doctype);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(9);
      if (lookahead == '/') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_quoted_attribute_value);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_unquoted_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead) &&
          lookahead != '`') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_tag_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__tag_whitespace);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__tag_whitespace);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<') ADVANCE(73);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(33);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(34);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(35);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(33);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(47);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(48);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(50);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(56);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(61);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(32);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_plain_ampersand);
      if (lookahead == '#') ADVANCE(14);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<') ADVANCE(73);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 18},
  [5] = {.lex_state = 18},
  [6] = {.lex_state = 18},
  [7] = {.lex_state = 18},
  [8] = {.lex_state = 18},
  [9] = {.lex_state = 18},
  [10] = {.lex_state = 18},
  [11] = {.lex_state = 18},
  [12] = {.lex_state = 18},
  [13] = {.lex_state = 18},
  [14] = {.lex_state = 18},
  [15] = {.lex_state = 18},
  [16] = {.lex_state = 18},
  [17] = {.lex_state = 18},
  [18] = {.lex_state = 18},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 4},
  [22] = {.lex_state = 4},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 4},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_doctype] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_quoted_attribute_value] = ACTIONS(1),
    [sym_tag_name] = ACTIONS(1),
    [sym__tag_whitespace] = ACTIONS(3),
    [sym_entity] = ACTIONS(1),
    [sym_plain_ampersand] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(43),
    [sym__node] = STATE(5),
    [sym_element] = STATE(5),
    [sym_start_tag] = STATE(2),
    [sym_self_closing_element] = STATE(9),
    [aux_sym_document_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_doctype] = ACTIONS(7),
    [anon_sym_LT] = ACTIONS(9),
    [sym__tag_whitespace] = ACTIONS(11),
    [sym_entity] = ACTIONS(7),
    [sym_plain_ampersand] = ACTIONS(13),
    [sym_text] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym__node] = STATE(3),
    [sym_element] = STATE(3),
    [sym_start_tag] = STATE(2),
    [sym_end_tag] = STATE(8),
    [sym_self_closing_element] = STATE(9),
    [aux_sym_document_repeat1] = STATE(3),
    [sym_doctype] = ACTIONS(15),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(17),
    [sym__tag_whitespace] = ACTIONS(11),
    [sym_entity] = ACTIONS(15),
    [sym_plain_ampersand] = ACTIONS(19),
    [sym_text] = ACTIONS(19),
  },
  [STATE(3)] = {
    [sym__node] = STATE(4),
    [sym_element] = STATE(4),
    [sym_start_tag] = STATE(2),
    [sym_end_tag] = STATE(12),
    [sym_self_closing_element] = STATE(9),
    [aux_sym_document_repeat1] = STATE(4),
    [sym_doctype] = ACTIONS(21),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_LT_SLASH] = ACTIONS(17),
    [sym__tag_whitespace] = ACTIONS(11),
    [sym_entity] = ACTIONS(21),
    [sym_plain_ampersand] = ACTIONS(23),
    [sym_text] = ACTIONS(23),
  },
  [STATE(4)] = {
    [sym__node] = STATE(4),
    [sym_element] = STATE(4),
    [sym_start_tag] = STATE(2),
    [sym_self_closing_element] = STATE(9),
    [aux_sym_document_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(25),
    [sym_doctype] = ACTIONS(27),
    [anon_sym_LT] = ACTIONS(30),
    [anon_sym_LT_SLASH] = ACTIONS(25),
    [sym__tag_whitespace] = ACTIONS(11),
    [sym_entity] = ACTIONS(27),
    [sym_plain_ampersand] = ACTIONS(33),
    [sym_text] = ACTIONS(33),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(9), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(36), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(9), 1,
      sym_self_closing_element,
    ACTIONS(21), 2,
      sym_doctype,
      sym_entity,
    ACTIONS(23), 2,
      sym_plain_ampersand,
      sym_text,
    STATE(4), 3,
      sym__node,
      sym_element,
      aux_sym_document_repeat1,
  [29] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(40), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(38), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [44] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(44), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(42), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [59] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(48), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(46), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [74] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(52), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(50), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [89] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(56), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(54), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [104] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(60), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(58), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [119] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(64), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(62), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [134] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(68), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(66), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [149] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(72), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [164] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(76), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(74), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [179] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(80), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
    ACTIONS(78), 4,
      ts_builtin_sym_end,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
  [194] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(82), 3,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
    ACTIONS(84), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
  [208] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(86), 3,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
    ACTIONS(88), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
  [222] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(90), 3,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
    ACTIONS(92), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
  [236] = 3,
    ACTIONS(11), 1,
      sym__tag_whitespace,
    ACTIONS(94), 3,
      sym_doctype,
      anon_sym_LT_SLASH,
      sym_entity,
    ACTIONS(96), 3,
      anon_sym_LT,
      sym_plain_ampersand,
      sym_text,
  [250] = 5,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(98), 1,
      anon_sym_GT,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(102), 1,
      sym_attribute_name,
    STATE(31), 1,
      sym_attribute,
  [266] = 5,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(102), 1,
      sym_attribute_name,
    ACTIONS(104), 1,
      anon_sym_GT,
    ACTIONS(106), 1,
      anon_sym_SLASH,
    STATE(31), 1,
      sym_attribute,
  [282] = 5,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(102), 1,
      sym_attribute_name,
    ACTIONS(108), 1,
      anon_sym_GT,
    ACTIONS(110), 1,
      anon_sym_SLASH,
    STATE(31), 1,
      sym_attribute,
  [298] = 4,
    ACTIONS(112), 1,
      anon_sym_GT,
    ACTIONS(114), 1,
      anon_sym_SLASH,
    ACTIONS(116), 1,
      sym__tag_whitespace,
    STATE(27), 1,
      aux_sym_start_tag_repeat1,
  [311] = 4,
    ACTIONS(98), 1,
      anon_sym_GT,
    ACTIONS(100), 1,
      anon_sym_SLASH,
    ACTIONS(118), 1,
      sym__tag_whitespace,
    STATE(28), 1,
      aux_sym_start_tag_repeat1,
  [324] = 3,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    STATE(33), 1,
      sym_attribute_value,
    ACTIONS(120), 2,
      sym_quoted_attribute_value,
      sym_unquoted_attribute_value,
  [335] = 4,
    ACTIONS(104), 1,
      anon_sym_GT,
    ACTIONS(106), 1,
      anon_sym_SLASH,
    ACTIONS(122), 1,
      sym__tag_whitespace,
    STATE(28), 1,
      aux_sym_start_tag_repeat1,
  [348] = 3,
    ACTIONS(126), 1,
      sym__tag_whitespace,
    STATE(28), 1,
      aux_sym_start_tag_repeat1,
    ACTIONS(124), 2,
      anon_sym_GT,
      anon_sym_SLASH,
  [359] = 4,
    ACTIONS(104), 1,
      anon_sym_GT,
    ACTIONS(106), 1,
      anon_sym_SLASH,
    ACTIONS(122), 1,
      sym__tag_whitespace,
    STATE(25), 1,
      aux_sym_start_tag_repeat1,
  [372] = 2,
    ACTIONS(131), 1,
      anon_sym_EQ,
    ACTIONS(129), 3,
      anon_sym_GT,
      anon_sym_SLASH,
      sym__tag_whitespace,
  [381] = 1,
    ACTIONS(124), 3,
      anon_sym_GT,
      anon_sym_SLASH,
      sym__tag_whitespace,
  [387] = 3,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(102), 1,
      sym_attribute_name,
    STATE(31), 1,
      sym_attribute,
  [397] = 1,
    ACTIONS(133), 3,
      anon_sym_GT,
      anon_sym_SLASH,
      sym__tag_whitespace,
  [403] = 1,
    ACTIONS(135), 3,
      anon_sym_GT,
      anon_sym_SLASH,
      sym__tag_whitespace,
  [409] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(137), 1,
      anon_sym_GT,
  [416] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(139), 1,
      sym_tag_name,
  [423] = 2,
    ACTIONS(137), 1,
      anon_sym_GT,
    ACTIONS(141), 1,
      sym__tag_whitespace,
  [430] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(143), 1,
      anon_sym_GT,
  [437] = 2,
    ACTIONS(145), 1,
      anon_sym_GT,
    ACTIONS(147), 1,
      sym__tag_whitespace,
  [444] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(149), 1,
      sym_tag_name,
  [451] = 2,
    ACTIONS(143), 1,
      anon_sym_GT,
    ACTIONS(151), 1,
      sym__tag_whitespace,
  [458] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(153), 1,
      anon_sym_GT,
  [465] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(155), 1,
      ts_builtin_sym_end,
  [472] = 2,
    ACTIONS(157), 1,
      anon_sym_GT,
    ACTIONS(159), 1,
      sym__tag_whitespace,
  [479] = 2,
    ACTIONS(161), 1,
      sym_tag_name,
    ACTIONS(163), 1,
      sym__tag_whitespace,
  [486] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(165), 1,
      anon_sym_GT,
  [493] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(167), 1,
      anon_sym_GT,
  [500] = 2,
    ACTIONS(165), 1,
      anon_sym_GT,
    ACTIONS(169), 1,
      sym__tag_whitespace,
  [507] = 2,
    ACTIONS(171), 1,
      sym_tag_name,
    ACTIONS(173), 1,
      sym__tag_whitespace,
  [514] = 2,
    ACTIONS(167), 1,
      anon_sym_GT,
    ACTIONS(175), 1,
      sym__tag_whitespace,
  [521] = 2,
    ACTIONS(3), 1,
      sym__tag_whitespace,
    ACTIONS(177), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(5)] = 0,
  [SMALL_STATE(6)] = 29,
  [SMALL_STATE(7)] = 44,
  [SMALL_STATE(8)] = 59,
  [SMALL_STATE(9)] = 74,
  [SMALL_STATE(10)] = 89,
  [SMALL_STATE(11)] = 104,
  [SMALL_STATE(12)] = 119,
  [SMALL_STATE(13)] = 134,
  [SMALL_STATE(14)] = 149,
  [SMALL_STATE(15)] = 164,
  [SMALL_STATE(16)] = 179,
  [SMALL_STATE(17)] = 194,
  [SMALL_STATE(18)] = 208,
  [SMALL_STATE(19)] = 222,
  [SMALL_STATE(20)] = 236,
  [SMALL_STATE(21)] = 250,
  [SMALL_STATE(22)] = 266,
  [SMALL_STATE(23)] = 282,
  [SMALL_STATE(24)] = 298,
  [SMALL_STATE(25)] = 311,
  [SMALL_STATE(26)] = 324,
  [SMALL_STATE(27)] = 335,
  [SMALL_STATE(28)] = 348,
  [SMALL_STATE(29)] = 359,
  [SMALL_STATE(30)] = 372,
  [SMALL_STATE(31)] = 381,
  [SMALL_STATE(32)] = 387,
  [SMALL_STATE(33)] = 397,
  [SMALL_STATE(34)] = 403,
  [SMALL_STATE(35)] = 409,
  [SMALL_STATE(36)] = 416,
  [SMALL_STATE(37)] = 423,
  [SMALL_STATE(38)] = 430,
  [SMALL_STATE(39)] = 437,
  [SMALL_STATE(40)] = 444,
  [SMALL_STATE(41)] = 451,
  [SMALL_STATE(42)] = 458,
  [SMALL_STATE(43)] = 465,
  [SMALL_STATE(44)] = 472,
  [SMALL_STATE(45)] = 479,
  [SMALL_STATE(46)] = 486,
  [SMALL_STATE(47)] = 493,
  [SMALL_STATE(48)] = 500,
  [SMALL_STATE(49)] = 507,
  [SMALL_STATE(50)] = 514,
  [SMALL_STATE(51)] = 521,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [36] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [38] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 6, 0, 0),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 6, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 8, 0, 0),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 8, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [54] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 4, 0, 0),
  [56] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 4, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 5, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 5, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 4, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 4, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 5, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 5, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_element, 7, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_element, 7, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 5, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 5, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 6, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 6, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [126] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [155] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [173] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [177] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_bevyml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "bevyml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
